version: "3.8"

volumes:
  iam_data:
    driver: local

services:
  db:
    image: mariadb:10.4
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      MYSQL_ROOT_PASSWORD: gsec
      MYSQL_DATABASE: gsec
      MYSQL_USER: gsec
      MYSQL_PASSWORD: gsec
    ports:
      - '3306:3306'
    restart: on-failure
    volumes:
      - ${PWD}/../../disks/gsec/sql:/var/lib/mysql

  db-iam:
    image: mariadb:10.4
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      MYSQL_ROOT_PASSWORD: iam
      MYSQL_DATABASE: iam
      MYSQL_USER: iam
      MYSQL_PASSWORD: iam
    ports:
      - '3307:3306'
    restart: on-failure
    volumes:
      - iam_data:/var/lib/mysql

  keycloak:
    image: jboss/keycloak:12.0.4
    ports:
      - "6080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=iam
      - DB_VENDOR=mariadb
      - DB_USER=iam
      - DB_PASSWORD=iam
      - DB_ADDR=db-iam
      - DB_DATABASE=iam
      - DB_PORT=3306
      - KEYCLOAK_LOGLEVEL=DEBUG
      - ROOT_LOGLEVEL=DEBUG
      - KEYCLOAK_IMPORT=/tmp/example-realm.json
    volumes:
      - ${PWD}/realm-export.json:/tmp/example-realm.json
      - ${PWD}/../../../../../provider/target/provider-0.0.1-SNAPSHOT.jar:/opt/jboss/keycloak/standalone/deployments/provider-0.0.1-SNAPSHOT.jar
    depends_on:
      - db-iam